---
title: "The Path Toward Omni-channel Retailing: How Large Language Model Facilitates the Process"
abstract: |
  Retail strategies have been evolving since its early inception that was comprised of mere simple acitivities. Omni-channel retail strategy is, undoubtedly, the most recent strategy attempting to provide a consistant, integrated customer experience across different channels, including online and offline ones. In this article, the marketing challenges commonly arise in the path towards omnichannel retailers are pointed out and the role of technology as a solution is explored deeply. Specifically, we will concentrate on Large Language Models, a type of Generative AI, to assess whether they have the ability to produce consistent advertising messages and convey characteristics of the retailer or not. 
keywords: 
  - retail
  - omnichannel retailing
  - integrated marketing communications
  - generative ai
  - large language models
  - natural language processing
bibliography: "https://api.citedrive.com/bib/45ed9c35-1341-4f53-ae0b-9bd087b2ebcd/references.bib?x=eyJpZCI6ICI0NWVkOWMzNS0xMzQxLTRmNTMtYWUwYi05YmQwODdiMmViY2QiLCAidXNlciI6ICIzNzQ2IiwgInNpZ25hdHVyZSI6ICI4YmYxNmFiZjZjNzdjYjExYWRhNGVmNjNhZGQ0OWU2NGE3OGY5NjAzMzQwN2ZhMDZiZmI0ZDFlZDA4MDQwMjljIn0=/bibliography.bib"
format: pdf
---

## 1. Introduction
The concept of omni-channel retailing is not limited to recent years, but due to new technologies and emerging tools, a large proportion of retailers have adopted such a strategy. More than a decade ago, the term "omni-channel" appeared as a way of interacting with the retailer, through which the customer feels consistency regardless of the channel the customer is using [@Rigbi2011]. The purpose of such a new strategy is to treat channels as interconnected touchpoints, enabling consumers to enjoy a seamless experience within an ecosystem [@Shen_2018]. The number of papers related to omni-channel in various journals has shown an upward trend [@Cai_2020], but various challenges inherent in the path toward an integrated and consistent experience demand additional efforts. Although this concept attracts both customers and retailers [@Hajdas_2022], related literature has not covered developments and it requires to conduct research regarding nuanced topics [@Saghiri_2017].

A channel represents any contact point or medium that a customer and the firm can interact with each other [@Neslin_2006]. One of the accepted definitions of omni-channel management is "the synergetic management of the numerous available channels and customer touchpoints, in such a way that the customer experience across channels and the performance over channels are optimized" [@Verhoef_2015]. In other words, the objective is to create a shopping journey in which customers feel a seamless experience across offline and online channels [@Bhatnagar_2004]. Omni-channel, however, is not the same as multi-channel (or multiple channel) due to lack of synergy or even cross-channel, which doesn't meet the level of required integration [@Li_2018; @Hajdas_2022]. 

The transition phases from a single- or multi-channel retailer toward channel integration and the creation of a seamless customer experience on different channels raise some serious issues that require appropriate management and tools. Technology, and specifically Artificial Intelligence (AI), has a multitude of capabilities that can streamline the process and result in omni-channel retailing with the necessary level of integration. This article seeks to explore the prospective benefits of Large Language Models (LLMs) for addressing the problems and challenges in the way of integrating retail channels. 

First, we review the literature to have a clear image of omni-channel retailing from different points of view to grasp what additional steps it requires to implement the strategy. Then, the role of technology and its unprecedented merits that can pave the way to become an omni-channel retailer are explored in the previous studies. Next, we discuss Large Language Models (LLMs hereafter) like ChatGPT and Bard that generate text in response to users prompts. Finally, we ask two commercial LLMs to generate marketing messages and evaluate them with Natural Language Processing (NLP hereafter) to evaluate if the messages meet the characteristics of integrated channels.

## 2. Literature Review
Retailing has evolved in various forms from the past to the present. Each new format, with its customized channels, has undergone testing to measure its efficiency and potential to serve customers satisfactorily. Considering the purchasing process allows us to explore the distinctive features of each format and identify their inherent strengths and weaknesses. One simplified yet insightful framework involves four major steps that customers typically follow: information search, purchase, acquisition, and returns [@Gauri_2021]. In traditional retail formats, the entire customer journey used to take place at a single physical channel. Nowadays, however, customers can opt for a combination of channels to fulfill their information search, product purchase, and acquisition, or even product return [@Kim_2008]. For example, some customers prefer to search offline and buy online, a practice widely known as showrooming [@Ailawadi_2017], or choose products to buy online and collect them at specific locations, known as click-and-collect [@Weltevreden_2008]. Even more complex, one can place an order in one channel (e.g., on a smartphone), receive the order via another channel (e.g., home delivery), and return it in case of an error through a third channel (e.g., a physical store) [@Kembro_2018]. Each channel has its own merits, and retailers would benefit from harnessing the advantages and mitigating the disadvantages of each channel.

n an omni-channel retailer, not only is customer value created through the design, deployment, coordination, and evaluation of its channels, but it also aims to integrate all touchpoints in a way that provides a seamless customer experience [@Thaichon_2022]. More specifically, a successful omni-channel management approach results in synergy among channels that contributes to overall effectiveness [@Melacini_2018]. Synergy exists as the channels of a retailer impact one another, a phenomenon that has been empirically studied. For example, an online channel is likely to earn more if it establishes an offline store in a region where its previous presence was not substantial [@Wang_2017].

One of the early studies in multiple channels management investigated the unexploited opportunities that businesses are often seeking [@Zhang_2010]. More recently, [@Shen_2018] attempted to answer what drives a retailer to seek an integrated and consistent shopping experience, suggesting that the quality of channel integration influences perceived fluency across channels. Increasing cell-phone usage and technological developments have been identified as two important factors [@Hajdas_2022]. Notably, in that article, channel integration quality comprises channel choice breadth, channel service transparency, content consistency, and process consistency. However, considering the internal and external obstacles in operationalizing an omni-channel strategy, achieving the ultimate goal of high levels of channel integration may be unattainable for industries with certain characteristics, making this strategy seem utopian for them [@Hajdas_2022].

There are numerous strategic decisions that departments should make, and processes have to be revised and coordinated when transitioning from a multi-channel or cross-channel to an omni-channel approach [@Cao_2014]. Operations and logistics are essential parts of this transition, but the domains of supply chain management and inventory management have not been discussed sufficiently yet [@Cai_2020]. Additionally, the unique characteristics of omni-channel retailing require innovations in warehouse operations as well [@Kembro_2018]. In this article, however, our focus will be on those aspects that directly affect customers' perceptions.

### 2.1 Marketing Challenges on the Omni-channel Transition Road 
The Marketing Science Institute placed a major emphasis on omni-channel retailing as an agenda for marketing research back in 2018 [@msi_2018]. Adding a new channel, whether online or offline, contributes to the bottom line, as demonstrated by an empirical study [@Wang_2017]. This study highlights the complementary effect of online and offline channels, despite their potential substitution effect in distribution. It emphasizes that opening a physical store or an online one becomes a strategic initiative in a competitive market. Retailers that initially established brick-and-mortar stores (e.g., Walmart, Target, and Kroger) aim to protect their market shares by launching and integrating their own online channels [@Jindal_2021]. The complementary effect also increases the willingness-to-pay of customers looking for expressive durable goods (goods that, unlike functional goods, cannot be assessed and compared before purchase and have higher uncertainties) in an omni-channel retailer compared to a pure online retailer [@Chatterjee_2017].

As mentioned earlier, each channel offers distinct benefits for both customers and sellers. Quick delivery is one of the areas where online channels have an advantage over offline ones, but it's not the only one. More importantly, a large assortment, competitive prices, and purchase convenience are the primary reasons why online retailers attract customers [@Jindal_2021]. However, a customer is likely to interact with multiple channels throughout their purchasing journey, rather than relying on just one. For instance, customers typically progress through various stages, starting with need recognition, followed by information search, purchase, and finally after-sales service, using separate channels or combinations of them [@Neslin_2006]. Therefore, offline stores also have features that add value to overall business goals. One study introduced the term "supercharging" to describe the valuable effects of customer-experience-focused offline brand stores with no inventory or instant fulfillment on customers' purchasing behavior. Supercharged customers, who have visited the store and had a positive brand experience, spend up to 60% more on average, make purchases more frequently, and have fewer returns [@Bell_2020].

On that basis, customer experience is a core marketing concept in omni-channel strategy that deserves attention in both research and practice. The quality of the overall experience is a key factor influencing customers' intent to shop and is crucial in determining the success of an omni-channel business [@Saghiri_2017]. It's defined as a multidimensional construct that encompasses customers' cognitive, emotional, behavioral, sensorial, and social responses to what a business offers at every touchpoint in the purchase journey [@Lemon_2016]. Nowadays, customers interact more frequently and through myriad touchpoints with a firm, which complicates the customer journey [@Lemon_2016]. Nonetheless, service integration, which consists of service consistency and transparency, is found to have a direct relationship with several aspects of customer experience (such as flow, referring to involvement in a specific activity without realizing time, and perceived privacy risk), resulting in repeat purchasing [@Quach_2022].

Additionally, marketing communication is one of the potential contributors to complementary effects. The main contribution of the article lies in the detection of the mechanism through which marketing communications drive complementarity. In this context, a source of synergy is the way informative advertisements by stores generate more sales for the online channel [@Wang_2017].

#### 2.1.1 Integrated Marketing Communications
The messages that customers receive at each step of their journey must be crafted in alignment with the value proposition of the retailer. In an omni-channel world, IMC (Integrated Marketing Communications) underpins the entire strategy, as service consistency makes it feasible. The primary goal is to send clear, consistent, and compelling brand and company messages through integrated and coordinated communication channels. [@e228abed85a142f0b132137f1932e959]. 

Similar to omni-channel retailing, the concept of an omni-channel approach to brand engagement emphasizes the need for IMC as a prerequisite for a unified brand experience. [@Manser_Payne_2017]. 

### 2.2 Technology as a Transition Facilitator
Among all the factors causing changes in retailing, technology enhancements and innovative devices can be identified as the leading ones. It's of utmost importance for retailers to reflect on strategies for positioning in the new dynamic marketplace [@Grewal_2021]. The article recognizes technology as the core enabler of the strategies related to the 6Ps of retailing. 

Customer-facing or shopper-facing technologies improve the customer's journey and their engagement with products, services, or brands [@Shankar_2021; @Grewal_2021]. A classification of such technologies and the drivers for adopting them has been studied [@Shankar_2021]. For instance, Artificial Intelligence (AI hereafter) has numerous applications, including sales/customer relationship management, personalization and recommendation systems, customer service management, supply chain optimization, inventory management, and store task creation. With the vast amount of data that is produced, collected, and analyzed, many retail technologies can be grouped into AI segment [@Grewal_2021]. 

Another newly adopted technology is Augmented Reality (AR hereafter) that has pushed omni-channel strategy one step further. One study points out the role of technologies like cell phones and AR in blurring retail channel boundaries and improving interactions with customers [@brynjolfsson2013competing]. Consequently, a reshaped competitive advantage should be considered by both retailers and their supply chain collaborators. It's suggested that AR blurs the boundaries between channels because of its combined offering of embedded, embodied, and extended experiences [@Hilken_2018]. Virtual try-on tools provide contextual information that used to be exclusively found in traditional stores, or AR can offer specialized and interactive information that was not possible for brick-and-mortar stores in the past. 

#### 2.2.1 Large Language Models
AI has been thriving in numerous businesses and industries. Goldman Sachs estimates that AI has the potential to increase global GDP by 7% in the next 10 years [@Generative-2023-09-23]. Customer-centric industries such as retail are projected to benefit more from marketing and sales AI applications than any other industries due to the vast amount of data generated through customer interactions [@Sizing-2023-09-23]. Recently, generative AI, a compelling subset of AI, has emerged in various fields and practices.

Generative AI is a set of computational techniques that can create new, meaningful content, such as text, images, and audio, thanks to its vast training data sets [@Feuerriegel_2023]. Large language models (LLM hereafter) have been advancing at an unprecedented pace enabling users to receive answers to their prompts. ChatGPT was released in November 2022, and within just a few months, an updated model called GPT-4 was introduced [@Economic-2023-09-23]. In May 2023, Google announced a new large language model, PaLM 2, which enhances its Bard chatbot [@Economic-2023-09-23].

Large language models like ChatGPT enable e-commerce businesses to significantly reduce their personnel resource costs by providing automated customer service and order fulfillment services [@Rivas_2023].

## 3. Coordinating Marketing Messages with LLMs
Our main contribution is to evaluate the marketing messages across different retail channels generated by commercialized and well-known LLMs. The customer should experience what the company has already intended, regardless of retail channel distribution so that conflicted messages or incompatible experience would hinder omni-channel strategy.

Channel integration, the ultimate objective in omni-channel retailing, can be studied from two main perspectives: the consumer approach and the retail approach [@Hajdas_2022]. In this study, we specifically focus on the former, aiming to evaluate whether LLMs are capable of producing marketing messages that foster a coherent brand experience.


## References






