---
title: "The Path Toward Omni-channel Retailing: How Large Language Model Facilitates Marketing Processes"
abstract: |
  Retailing has evolved in numerous ways to cater to customers with diverse needs and shopping behaviors. The products offered by a retailer can be accessed through various channels, such as traditional physical stores, websites, or mobile applications. However, the latest strategy, known as omni-channel retailing, emphasizes the customer journey rather than individual channels. This article reviews the characteristics of omni-channel retailing, focusing specifically on its unique marketing aspects and operations. We then explore the potential contributions of Large Language Models (LLMs) in achieving greater consistency and integration across channels, ultimately enhancing the customer experience. *findings*...
keywords: 
  - retail
  - omni-channel retailing
  - integrated marketing communications
  - generative ai
  - large language models
  - natural language processing
bibliography: "https://api.citedrive.com/bib/45ed9c35-1341-4f53-ae0b-9bd087b2ebcd/references.bib?x=eyJpZCI6ICI0NWVkOWMzNS0xMzQxLTRmNTMtYWUwYi05YmQwODdiMmViY2QiLCAidXNlciI6ICIzNzQ2IiwgInNpZ25hdHVyZSI6ICI4YmYxNmFiZjZjNzdjYjExYWRhNGVmNjNhZGQ0OWU2NGE3OGY5NjAzMzQwN2ZhMDZiZmI0ZDFlZDA4MDQwMjljIn0=/bibliography.bib"
format: pdf
execute: 
  echo: false
  cache: false
  warning: false
---

# 1. Introduction
The concept of omni-channel retailing has been around for some time, but recent technological advancements and emerging tools have led to its adoption by a larger proportion of retailers. Over a decade ago, the term “omni-channel” emerged as a method of interaction with retailers, providing customers with a consistent experience regardless of the channel they use [@Rigbi2011]. The primary goal is to treat channels as interconnected touchpoints, enabling consumers to enjoy a seamless experience within an ecosystem [@Shen_2018]. Omni-channel management is another related concept that must be considered. The definition @Verhoef_2015 have provided is accepted by many scholars; it is the synergetic management of the numerous available channels and customer touchpoints, in such a way that the customer experience across channels and the performance over channels are optimized. 

A channel is any point of contact or medium through which a customer and a firm can interact [@Neslin_2006]. The goal is to create a shopping journey that provides customers with a seamless experience across offline and online channels [@Bhatnagar_2004]. Omni-channel is distinct from multi-channel (or multiple channel) due to the lack of synergy, and even cross-channel, which does not meet the required level of integration [@Li_2018; @Hajdas_2022]. However, the transition from single-channel or even multi-channel to omni-channel is fraught with challenges, some of which may be effectively resolved or at least mitigated with new developments that have not been fully studied [@Saghiri_2017].

The rise of Large Language Models (LLMs), a subset of generative artificial intelligence, has caused significant disruptions in recent years, and more changes are anticipated. Businesses, particularly marketing teams, can greatly benefit from artificial intelligence (AI) due to its wide range of applications. However, 64% of marketers lack sufficient knowledge, indicating that there is still a long way to go in fully utilizing AI in marketing [@Long-2023-11-15]. In this article, we aim to illuminate the capabilities of LLMs, particularly in the sphere of omni-channel retailing, as a step towards bridging this knowledge gap.

This paper explores the role of LLMs in facilitating the transition from a single-channel to an omni-channel retailing strategy. LLMs can contribute to the development of effective integrated marketing communications (IMC), which is crucial for successful omni-channel retailing. The consistent and aligned language generated by LLMs can effectively convey the desired retailer image to targeted customer segments. Also, throughout the customer journey, LLMs are capable of providing desired touchpoints that might not be easily plausible otherwise. *More specifically, we found if marketing teams ask LLMs for campaign messages across channels, they would receive compelling sentences using imperative words to convey desired characteristics. Although this finding suggests that LLMs could be added to the workflow or even automate a part of the process of omni-channel marketing activities, relying solely on the unexplored technology may not be a wise decision.*

# 2. Literature Review
Retailing has evolved into various forms from the past to the present. Each new format, with its customized channels, served customers with its unique experience. Considering the purchasing process allows us to explore the distinctive features of each format and identify their inherent strengths and weaknesses. One simplified yet insightful framework involves four major steps that customers typically follow: information search, purchase, acquisition, and returns [@Gauri_2021]. In traditional retail formats, the entire customer journey used to take place at one physical channel. Nowadays, however, customers can opt for a combination of channels to fulfill their information search, product purchase, and acquisition, or even product return [@Kim_2008]. For example, some customers prefer to search offline and buy online, a practice widely known as showrooming [@Ailawadi_2017], or choose products to buy online and collect them at specific locations, known as click-and-collect [@Weltevreden_2008]. Even more complex, one can place an order in one channel (e.g., on a smartphone), receive the order via another channel (e.g., home delivery), and return it in case of an error through a third channel (e.g., a physical store) [@Kembro_2018]. Each channel has its own merits, and retailers would benefit from harnessing the advantages and mitigating the disadvantages of each.

Customers and retailers have been attracted to omni-channel retailing [@Hajdas_2022] along with researchers as the number of papers covering the topic has risen sharply [@Cai_2020]. Researchers attempt to explain numerous strategic decisions that departments should make, and processes have to be revised and coordinated when transitioning from a multi-channel or cross-channel to an omni-channel retailing [@Cao_2014]. Operations and logistics are essential parts of this transition, but the domains of supply chain management and inventory management have not been discussed sufficiently yet [@Cai_2020]. Additionally, the unique characteristics of omni-channel retailing require innovations in warehouse operations as well [@Kembro_2018]. In this article, however, our focus will be on those aspects that directly affect customers' perceptions. Marketing omni-channel comprises of new features that must be taken into account, such as service consistency across channels in order to create an integrated customer journey.

## 2.1 Omni-channel Marketing and the Role of Communication
The Marketing Science Institute placed a major emphasis on omni-channel retailing as an agenda for marketing research back in 2018 [@msi_2018]. Adding a new channel, whether online or offline, contributes to the bottom line, as demonstrated by an empirical study [@Wang_2017]. @Wang_2017 highlights the complementary effect of online and offline channels, despite their potential substitution effect in distribution. It emphasizes that opening a physical store for a first-online retailer or an online one for first-offline retailer becomes a strategic initiative in a competitive market. Retailers that initially established brick-and-mortar stores (e.g., Walmart, Target, and Kroger) aim to protect their market shares by launching and integrating their own online channels [@Jindal_2021]. The complementary effect also increases the willingness-to-pay of customers looking for expressive durable goods (goods that, unlike functional goods, cannot be assessed and compared before purchase and have higher uncertainties) in an omni-channel retailer compared to a pure online retailer [@Chatterjee_2017].

As mentioned earlier, each channel offers distinct benefits for both customers and sellers. Quick delivery is one of the areas where online channels have an advantage over offline ones, but it is not the only one. More importantly, a larger assortment, competitive prices, and purchase convenience are the primary reasons why online retailers attract customers [@Jindal_2021]. However, a customer is likely to interact with multiple channels throughout their purchasing journey, rather than relying on just one. For instance, customers typically progress through various stages, starting with need recognition, followed by information search, purchase, and finally after-sales service, using separate channels or combinations of them [@Neslin_2006]. Therefore, offline stores also have features that add value to overall business goals. One study introduced the term "supercharging" to describe the valuable effects of customer-experience-focused offline brand stores with no inventory or instant fulfillment on customers' purchasing behavior. Supercharged customers, who have visited the store and had a positive brand experience, spend up to 60% more on average, make purchases more frequently, and have fewer returns [@Bell_2020].

On that basis, customer experience is a core marketing concept in omni-channel strategy that deserves attention in both research and practice. The quality of the overall experience is a key factor influencing customers' intent to shop and is crucial in determining the success of an omni-channel business [@Saghiri_2017]. Customer experience can be defined as a multidimensional construct that encompasses customers' cognitive, emotional, behavioral, sensorial, and social responses to what a business offers at every touchpoint in purchasing process [@Lemon_2016]. Nowadays, customers interact more frequently and through myriad touchpoints with a firm, which complicates the customer journey [@Lemon_2016]. Nonetheless, service integration, which consists of service consistency and transparency, is found to have a direct relationship with several aspects of customer experience (such as flow, referring to involvement in a specific activity without realizing time, and perceived privacy risk), resulting in repeat purchasing [@Quach_2022].

Additionally, marketing communication is one of the potential contributors to complementary effects. The main contribution of the article lies in the detection of the mechanism through which marketing communications drive complementarity. In this context, a source of synergy is the way informative advertisements by stores generate more sales for the online channel [@Wang_2017].

### 2.1.1 Integrated Marketing Communications

## 2.2 Technology as a Transition Facilitator
### 2.2.1 Large Language Models

# 3. Methodology
# 4. Results
# 5. Conclusion

# Technology


