---
title: "The Path Towards Omnichannel Retailing: How Large Language Models Can Integrate Marketing Communications"
abstract: |
  Retailing has evolved significantly to cater to customers with diverse needs and shopping behaviors. Customers can access a retailer’s products through various channels, including traditional physical stores, websites, and mobile applications. The latest strategy, known as omnichannel retailing, emphasizes a seamless customer journey across these channels. This article reviews the characteristics of omnichannel retailing, with a specific focus on its marketing aspects and operations. We explore the potential contributions of Large Language Models (LLMs) in achieving greater consistency and integration across channels, thereby enhancing the customer experience. We propose that placing an LLM at the core of content generation can ensure consistent communication with customers across all channels. Furthermore, we simulated customer types extracted from clustering Amazon product reviews and evaluated their satisfaction after receiving LLM-generated content. We concluded that customer satisfaction is higher compared to the previous state.
keywords: 
  - Omnichannel retailing
  - Integrated marketing communications
  - Generative AI
  - Large language models
  - Natural language processing
bibliography: "https://api.citedrive.com/bib/45ed9c35-1341-4f53-ae0b-9bd087b2ebcd/references.bib?x=eyJpZCI6ICI0NWVkOWMzNS0xMzQxLTRmNTMtYWUwYi05YmQwODdiMmViY2QiLCAidXNlciI6ICIzNzQ2IiwgInNpZ25hdHVyZSI6ICI4YmYxNmFiZjZjNzdjYjExYWRhNGVmNjNhZGQ0OWU2NGE3OGY5NjAzMzQwN2ZhMDZiZmI0ZDFlZDA4MDQwMjljIn0=/bibliography.bib"
format: pdf
execute: 
  echo: false
  cache: false
  warning: false
---

# 1. Introduction
The concept of omni-channel retailing has been prevalent for some time. However, recent technological advancements and emerging tools have led to its wider adoption by retailers. Over a decade ago, the term “omnichannel” emerged as a method of interaction with retailers, aiming to provide customers with a consistent experience across all channels [@Rigbi2011]. The primary goal is to treat channels as interconnected touchpoints, enabling consumers to enjoy a seamless experience within an ecosystem [@Shen_2018]. Omnichannel management is another related concept that must be considered. The definition @Verhoef_2015 has suggested is accepted by many scholars; it is the synergetic management of the numerous available channels and customer touchpoints in such a way that the customer experience across channels and the performance over channels are optimized. 

A channel is any point of contact or medium through which a customer and a firm can interact [@Neslin_2006]. The goal is to create a shopping journey that provides customers a seamless experience across offline and online channels [@Bhatnagar_2004]. Omnichannel retailing is distinct from multichannel retailing due to the lack of synergy and even cross-channel retailing, which does not meet the required level of integration among channels [@Li_2018, Hajdas_2022]. However, the transition from single-channel or multichannel to omnichannel is fraught with challenges. Some of these challenges may be effectively resolved or at least mitigated with new developments that have not been fully studied [@Saghiri_2017]. One such challenge we focus on is the isolated conversations with customers that undermine the main purpose of omnichannel retailing.

The advent of Large Language Models (LLMs), a subset of generative artificial intelligence, has caused significant disruptions in recent years, with more changes anticipated. Businesses, particularly marketing teams, can greatly benefit from artificial intelligence (AI) due to its wide range of applications. However, 64% of marketers lack sufficient knowledge, indicating that there is still a long way to go in fully utilizing AI in marketing [@Long-2023-11-15]. In this article, we aim to illuminate the capabilities of LLMs, particularly in omnichannel retailing, as a step towards bridging this knowledge gap. Unlike chatbots and automated email marketing, LLMs generate human-like content, making conversations with customers more realistic and engaging. We propose that placing LLMs at the core of marketing communications significantly contributes to the desired level of channel integration. This is because it can serve customers throughout their purchase journey regardless of the channel they use. Furthermore, given sufficient descriptions, LLMs can simulate human responses, allowing for the evaluation of customer satisfaction after sending content to the actual customer.

First, we provide a concise literature review to clarify the aspects of omnichannel retailing and marketing. Next, we highlight the importance of Integrated Marketing Communications (IMC) in an omnichannel strategy. Subsequently, we illustrate how LLMs can contribute to consistent and integrated communications with shoppers, presenting the results of testing our proposed framework on several products. Finally, we conclude by discussing the benefits of our proposed framework and its relationship with other relevant studies.

# 2. Literature Review
Retailing has evolved significantly from the past to the present, with each new format offering a unique customer experience through its customized channels. By considering the purchasing process, we can explore the distinctive features of each format and identify their inherent strengths and weaknesses. @Lemon_2016 conceptualized the customer experience as a journey in three general steps: prepurchase, purchase, and postpurchase, with each step encompassing several behaviors. A simplified yet insightful framework involves four major behaviors that customers typically engage in: information search, purchase, acquisition, and returns [@Gauri_2021]. In traditional retail formats, the entire customer journey used to take place through a single physical channel. However, customers can now opt for a combination of channels to fulfill their information search, product purchase, acquisition, or even product return [@Kim_2008]. For example, some customers prefer to search offline and buy online, a practice widely known as showrooming [@Ailawadi_2017], or choose products to buy online and collect them at specific locations, known as click-and-collect [@Weltevreden_2008]. Even more complex, a customer can place an order in one channel (e.g., on a smartphone), receive the order via another channel (e.g., home delivery), and return it in case of an error through a third channel (e.g., a physical store) [@Kembro_2018]. Each channel has its own merits, and retailers would benefit from harnessing the advantages and mitigating the disadvantages of each by combining them, accounting for their bidirectional impacts. The more the boundaries between channels are blurred, the more satisfying the customer experience becomes, which is the ultimate goal of omnichannel retailing.

Customers and retailers have been attracted to omni-channel retailing [@Hajdas_2022] along with researchers as the number of papers covering the topic has risen sharply [@Cai_2020]. Researchers attempt to explain the numerous strategic decisions that departments should make and the processes that need to be revised and coordinated when transitioning from a multichannel or cross-channel approach to omnichannel retailing [@Cao_2014]. While operations and logistics are essential parts of this transition, the domains of supply chain management and inventory management have not yet been sufficiently discussed [@Cai_2020]. Additionally, the unique characteristics of omni-channel retailing require innovations in warehouse operations as well [@Kembro_2018]. In this article, however, our focus will be on those aspects that directly affect customers' perceptions. The concept of omnichannel marketing introduces new elements, such as service consistency, which directly impacts customer experience and loyalty [@Quach_2022]. Importantly, marketing communications should be strategically adjusted to blur the boundaries between channels, thereby creating a consistent and integrated customer journey that enhances the overall retail experience.

## 2.1 Omni-channel Marketing and the Role of Communication
The Marketing Science Institute placed a major emphasis on omni-channel retailing as an agenda for marketing research back in 2018 [@msi_2018]. Multichannel marketing is a strategy that allows companies to establish enduring relationships with their customers. It does this by providing customers and potential customers with information, products, services, and support through two or more channels that are synchronized [@doi:10.1177/1094670506293559]. The ongoing digital expansion has led customers to interact with businesses through various channels, prompting a shift towards "omnichannel" marketing that prioritizes a unified customer experience over mere transaction facilitation [@CuiUnknownTitle2020]. If the primary goal is to maximize the effectiveness of each individual channel, then the company is employing multi-channel marketing strategies. However, if the focus shifts to maximizing customer profitability across all channels, then the company is utilizing omnichannel marketing strategies [@Verhoef_2015].

As mentioned earlier, each channel offers distinct benefits for both customers and sellers. Quick delivery is one of the areas where online channels have an advantage over offline ones, but it is not the only one. More importantly, a larger assortment, competitive prices, and purchase convenience are the primary reasons why online retailers attract customers [@Jindal_2021]. However, a customer is likely to interact with multiple channels throughout their purchasing journey rather than relying on just one. For instance, customers typically progress through various stages, starting with need recognition, followed by information search, purchase, and finally, after-sales service, using separate channels or combinations of them [@Neslin_2006]. Therefore, offline stores also have features that add value to overall business goals. @Breugelmans_2023 suggested five major benefits that give reasons for customers to visit physical stores: discovery, convenience, customization, community, and shoppertainment (shopping and entertainment). One study introduced the term "supercharging" to describe the valuable effects of customer-experience-focused offline brand stores with no inventory or instant fulfillment on customers' purchasing behavior. Supercharged customers who have visited the store and had a positive brand experience spend up to 60% more on average, make purchases more frequently, and have fewer returns [@Bell_2020].

Adding a new channel, whether online or offline, contributes to the bottom line, as demonstrated by an empirical study [@Wang_2017]. @Wang_2017 highlights the complementary effect of online and offline channels despite their potential substitution effect in distribution. It emphasizes that opening a physical store for a first-online retailer or an online one for first-offline retailer becomes a strategic initiative in a competitive market. Retailers that initially established brick-and-mortar stores (e.g., Walmart, Target, and Kroger) aim to protect their market shares by launching and integrating their own online channels [@Jindal_2021]. The complementary effect also increases the willingness-to-pay of customers looking for expressive durable goods (goods that, unlike functional goods, cannot be assessed and compared before purchase and have higher uncertainties) in an omnichannel retailer compared to a pure online retailer [@Chatterjee_2017]. These effects relate to the complimentary impacts one channel has on another channel, which creates a delightful customer experience.

On that basis, customer experience is a core marketing concept in omnichannel strategy that deserves attention in both research and practice. Customer experience can be defined as a multidimensional construct that encompasses customers' cognitive, emotional, behavioral, sensorial, and social responses to what a business offers at every touchpoint in the purchasing process [@Lemon_2016]. The quality of the overall experience is a key factor influencing customers' intent to shop and is crucial in determining the success of an omnichannel business [@Saghiri_2017]. Nowadays, customers interact more frequently and through myriad touch points with a firm, which complicates the customer journey [@Lemon_2016]. @F_lstad_2018 defines customer journey as the usual way that a customer follows to reach or utilize a company’s product or service. The customer journey is the real process that shapes the customer experience and helps to comprehend how customer objectives, anticipations, and actions change over time [@OlsonUnknownTitle2019]. Nonetheless, service integration, which consists of service consistency and transparency, is found to have a direct relationship with several aspects of customer experience (such as flow, referring to involvement in a specific activity without realizing the time, and perceived privacy risk), resulting in repeat purchasing [@Quach_2022]. One aspect of service consistency should happen in the communications retailers usually have with customers throughout their journey. @OhUnknownTitle2012 state that information technology allows retailers to create an integrated communication system where the website not only provides after-sales support for products purchased in physical stores but also offers real-time live chat, giving online customers immediate access to customer service assistants. In addition, informative advertisements by stores generate more sales for the online channel, which demonstrates the synergy omnichannel retailing engenders [@Wang_2017]. Indeed, marketing communication is pivotal in crafting a unique customer experience and positively impacting the bottom line. This article's primary contribution is a framework that enables multichannel retailers to leverage the capabilities of Large Language Models (LLMs) for content generation, thereby facilitating the creation of an omnichannel environment.

### 2.1.1 Integrated Marketing Communications in Omni-channel Strategy
Content consistency has been identified as one of the prerequisites to integrate channels and create an omnichannel environment. @HossainUnknownTitle2020 developed a framework in which three fundamental aspects of channel integration quality (INQ) are suggested, and one of them is content consistency, including information consistency as a subdimension. @Shen_2018 also emphasized the importance of content consistency in the determination of channel integration quality. As a result, if a retailer aims to transform from a multichannel to an omnichannel, it has to enhance the quality of integration, so content consistency plays a major role. 

The primary goal of Integrated Marketing Communications (IMC) is to send clear, consistent, and compelling brand and company messages through integrated and coordinated communication channels [@e228abed85a142f0b132137f1932e959]. In an omnichannel world, IMC underpins the entire strategy, as service consistency is at the heart of channels unification. The messages that customers receive at each step of their journey must be crafted in alignment with the value proposition of the retailer. This is a business capability that enables a company to convert its communication resources and brand assets into market-driven results or returns on these assets [@doi:10.1080/00913367.2014.934938]. 

The shift towards omni-channel marketing has amplified the necessity for an interactive approach to IMC. In this approach, organizational barriers are reduced to foster communication synergies that boost customer engagement through a cohesive brand experience [@hansen2015hummel]. The unification of various tools and platforms into a single-choice environment leads to personalized information, acquisition, and usage [@RoccoUnknownTitle2016, ManserPayneUnknownTitle2017]. 

# 3. Integrated Communication with Large Language Models
Large language models have emerged as a technology disruption, especially in business and marketing. Nonetheless, in customer journey literature, technological disruption has not been explored enough [@Tueanrat_2021]. Our proposition contributes to identifying LLMs applications in the customer journey. We aim to customize customer interactions at specific touch points with the retailer through the power of content generation of LLMs. Improving these touchpoints has a direct impact on marketing outcomes. For instance, customer satisfaction depends on fulfilling interactions [@Halvorsrud_2016], while customer dissatisfaction and higher churn rates result from confusing and frustrating interactions [@Ieva_2018]. Thus, our proposition is expected to impact customer satisfaction directly.

@doi:10.1177/1094670506293559 noted the importance of customer segmentation in designing of multichannel strategy, and we have used customer segmentation to obtain different sorts of characteristics and personal feelings towards a product to better communicate with shoppers.


# 4. Results
# 5. Conclusion

# Technology


